### ISSUE TITLE
Lookup table from RAT - error

### ISSUE THREAD

**Issue by GvdDool** [pcraster/pcraster#364]
Hi, 

I am getting an error while running 'Lookup table from RAT', other tools are also not behaving as expected, and I think it's related, but I don't know how to solve this. 
I copied the tool output:
QGIS version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.5.1
GEOS version: 3.10.3-CAPI-1.16.1
PROJ version: Rel. 9.1.0, September 1st, 2022
PDAL version: 2.4.3 (git-version: 6311a6)
PCRaster version: QGIS PCRaster Provider version 0.2.0
Algorithm started at: 2022-09-20T15:25:50
Algorithm 'Lookup table from RAT' starting…
Input parameters:
{ 'INPUT' : 'E:/01_RiverFlood/PCRaster/DEM_cleanLDDstream.map', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 139, in processAlgorithm
self.to_csv(rat, output_lookup_table, table_type)
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 82, in to_csv
col_count = rat.GetColumnCount()
AttributeError: 'NoneType' object has no attribute 'GetColumnCount'

Execution failed after 0.06 seconds

Loading resulting layers
Algorithm 'Lookup table from RAT' finished

**Comment by GvdDool** [comment]
I don't seem to get this tool to work properly, today I got another error:
Traceback (most recent call last):
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 134, in processAlgorithm
if metadata['PCRASTER_VALUESCALE'] == 'VS_SCALAR':
KeyError: 'PCRASTER_VALUESCALE'

**Comment by jvdkwast** [comment]
This issue belongs to the PCRaster Tools plugin. Continuing in the PCRaster Tools repository: [https://github.com/jvdkwast/qgis-processing-pcraster/issues/49#issue-1387347716](https://github.com/jvdkwast/qgis-processing-pcraster/issues/49#issue-1387347716)
