### ISSUE TITLE
The test `python_pcrcalcpy_pythonunittest` fails with NumPy 1.26.2 (Mac ARM)

### ISSUE THREAD

**Issue by nilason** [pcraster/pcraster#388]
The `python_pcrcalcpy_pythonunittest` fails on two tests with NumPy 1.26.2 for Python 3.11 (on Mac ARM).

```
======================================================================
FAIL: test_003 (testNumPy.TestNumPy.test_003)
pcr2numpy should not run out of memory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_nilason_ports_gis_pcraster/pcraster/work/build/source/pcraster_python/testNumPy.py", line 611, in test_003
    self.assertEqual(mem_increase, False)
AssertionError: True != False

======================================================================
FAIL: test_numpy2pcr (testNumPy.TestNumPy.test_numpy2pcr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_nilason_ports_gis_pcraster/pcraster/work/build/source/pcraster_python/testNumPy.py", line 468, in test_numpy2pcr
    self.assertEqual(pcraster.cellvalue(raster, 2, 1), (0, True))
AssertionError: Tuples differ: (nan, False) != (0, True)

First differing element 0:
nan
0

- (nan, False)
+ (0, True)
````

**Comment by OliverSchmitz** [comment]
- [ ] #399
- [ ] #400
