### ISSUE TITLE
[Bug]: Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql

### ISSUE THREAD

**Issue by hernanrr** [pcraster/pcraster#409]
### Describe the bug

Upon successfully compiling from source on macOS Sequoia (15.1.1 (24B91)) on a 2020 Intel Macbook Air, and adding environmental variables, the program fails to run. Specifically, running a command like `pcrcalc --help` or trying to import the pcraster module inside a python interpreter fails with the error `Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql`. I suspect the installed program is not finding any of the libraries. 

### Expected behaviour

Upon issuing the command `pcrcalc --help` I expected help documentation. Instead, the following error was produced:

`dyld[10201]: Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql`
  `Referenced from: <20B3D3C3-D508-3EA3-80E7-AD0371333396> /Users/ricardo/pcraster-4.3.3/bin/pcrcalc`
  `Reason: tried: '$ORIGIN/../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../lib/QtSql.framework/Versions/A/QtSql' (no such file)`
`zsh: abort      pcrcalc --help`

Alternatively, inside the python interpreter, importing pcraster fails with the following error
```
>>> import pcraster
Traceback (most recent call last):
  File "/Users/ricardo/pcraster-4.3.3/python/pcraster/__init__.py", line 20, in <module>
    from ._pcraster import *
ImportError: dlopen(/Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so, 0x0002): Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql
  Referenced from: <DB16EEFD-2A65-3FD6-9C71-E9B9610E4DF5> /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so
  Reason: tried: '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import pcraster
  File "/Users/ricardo/pcraster-4.3.3/python/pcraster/__init__.py", line 59, in <module>
    raise ImportError(msg)
ImportError: dlopen(/Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so, 0x0002): Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql
  Referenced from: <DB16EEFD-2A65-3FD6-9C71-E9B9610E4DF5> /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so
  Reason: tried: '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file)
In case you cannot solve the issue please consult the PCRaster mailing list at:
https://lists.geo.uu.nl/mailman/listinfo/pcraster-info
```

### Steps to reproduce

Following the instructions in https://pcraster.geo.uu.nl/pcraster/4.4.1/documentation/pcraster_project/build.html, these are the commands given for compilation: 

1.  cmake -G"Unix Makefiles" ../pcraster -DCMAKE_INSTALL_PREFIX=$HOME/pcraster-4.3.3 -DCURSES_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/ -DCMAKE_PREFIX_PATH=/Users/ricardo/Qt/6.8.1//macos/lib/cmake/Qt6/ -DPython3_EXECUTABLE:FILEPATH=/usr/bin/python3.13 -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
2.   NR_CPUS=4
3.   cmake --build . --target all -- -j$NR_CPUS
4.   cmake --build . --target install

The configuration command is different than the one in the documentation to allow the configuration to find the relevant libraries. The output of each step is provided:

1. [cmake-config_output.txt](https://github.com/user-attachments/files/18158245/cmake-config_output.txt)
2. [build_output.txt](https://github.com/user-attachments/files/18158243/build_output.txt)
3. [build-install_output.txt](https://github.com/user-attachments/files/18158244/build-install_output.txt)

The first way to reproduce the error is to issue the command `pcrcalc --help`, which fails with the error 
```
dyld[10201]: Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql
  Referenced from: <20B3D3C3-D508-3EA3-80E7-AD0371333396> /Users/ricardo/pcraster-4.3.3/bin/pcrcalc
  Reason: tried: '$ORIGIN/../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../lib/QtSql.framework/Versions/A/QtSql' (no such file)
zsh: abort      pcrcalc --help
```

The second way in within the python interpreter: 
```
>>> import pcraster
Traceback (most recent call last):
  File "/Users/ricardo/pcraster-4.3.3/python/pcraster/__init__.py", line 20, in <module>
    from ._pcraster import *
ImportError: dlopen(/Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so, 0x0002): Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql
  Referenced from: <DB16EEFD-2A65-3FD6-9C71-E9B9610E4DF5> /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so
  Reason: tried: '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import pcraster
  File "/Users/ricardo/pcraster-4.3.3/python/pcraster/__init__.py", line 59, in <module>
    raise ImportError(msg)
ImportError: dlopen(/Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so, 0x0002): Library not loaded: @rpath/QtSql.framework/Versions/A/QtSql
  Referenced from: <DB16EEFD-2A65-3FD6-9C71-E9B9610E4DF5> /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so
  Reason: tried: '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file), '$ORIGIN/../../lib/QtSql.framework/Versions/A/QtSql' (no such file)
In case you cannot solve the issue please consult the PCRaster mailing list at:
https://lists.geo.uu.nl/mailman/listinfo/pcraster-info
```

### Additional information

I'm using: 

- PCRaster version 4.5.0-dev, cloned from the GitHub repository on 
- Python version 3.13.0
- Operating system: macOS Sequoia (15.1.1 (24B91)), x86_64 architecture
- Compiler ID: clang
- Compiler version: 16.0.0.16000026
- Qt: 6.8.1
- GDAL: 3.11.0dev-109b561268
- NumPy: 2.2.0
- pybind11: 2.13.6
-

**Comment by hernanrr** [comment]
After some finagling and much help from ChatGPT, I was able to get everything up and running. I suppose this would have been easier for someone more experienced with build configurations. Alas, I'm not that person. 

The following summarizes the steps I took to resolve the issues for **pcrcalc**, the **Python interpreter import**, and **aguila** and other binaries that were failing (it written by ChatGPT but supervised, verified and approved by me):

---

### Steps Taken to Solve the Issues

#### 1. **Issue with `pcrcalc` and Missing `QtSql.framework`**
The problem was caused by the dynamic linker failing to locate the `QtSql.framework` library at runtime.

**Solution:**
- Identified the correct path to `QtSql.framework`:
  ```
  /Users/ricardo/Qt/6.8.1/macos/lib/QtSql.framework/Versions/A/QtSql
  ```
- Fixed the `@rpath` for `pcrcalc` using `install_name_tool`:
  ```bash
  install_name_tool -add_rpath /Users/ricardo/Qt/6.8.1/macos/lib /Users/ricardo/pcraster-4.3.3/bin/pcrcalc
  ```
- Verified the `@rpath` update with `otool -l`:
  ```bash
  otool -l /Users/ricardo/pcraster-4.3.3/bin/pcrcalc | grep -A 2 RPATH
  ```

---

#### 2. **Issue Importing `pcraster` in Python**
Attempting to import `pcraster` in the Python interpreter raised a similar error related to `QtSql.framework` in `_pcraster.cpython-313-darwin.so`.

**Solution:**
- Added the `QtSql` path to `_pcraster.cpython-313-darwin.so`:
  ```bash
  install_name_tool -add_rpath /Users/ricardo/Qt/6.8.1/macos/lib /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so
  ```
- Verified the fix with:
  ```bash
  otool -l /Users/ricardo/pcraster-4.3.3/python/pcraster/_pcraster.cpython-313-darwin.so | grep -A 2 RPATH
  ```

---

#### 3. **Issue with `aguila` and Missing `QtSql.framework`**
The `aguila` tool faced the same issue with `QtSql.framework` as `pcrcalc`.

**Solution:**
- Systematically fixed the `@rpath` for all binaries in the PCRaster `bin` directory:
  ```bash
  for binary in /Users/ricardo/pcraster-4.3.3/bin/*; do
    if [[ -x "$binary" && ! -d "$binary" ]]; then
      install_name_tool -add_rpath /Users/ricardo/Qt/6.8.1/macos/lib "$binary"
    fi
  done
  ```
- Verified the update for `aguila`:
  ```bash
  otool -l /Users/ricardo/pcraster-4.3.3/bin/aguila | grep -A 2 RPATH
  ```
- Confirmed the issue was resolved by running:
  ```bash
  aguila --help
  ```

---

### Observations
The issue seems to stem from how the `@rpath` entries are configured during the build and installation process. Adding the correct `Qt` library paths manually resolves the problem, but this step should ideally be handled during the build configuration.

Additionally, the above assumes the user has sufficient privileges to run all commands. I found it necessary to `sudo` my way through some of them. 

---

### Recommendation to Package Maintainers (as suggested by ChatGPT, as I, unfortunately do not know enough about this and can only test by doing)

To avoid runtime errors related to missing shared libraries (e.g., `QtSql.framework`, `libgdal.36.dylib`), I recommend updating the **CMake configuration** to include explicit `RPATH` settings during the build process. This ensures that all PCRaster tools can locate the required dynamic libraries without relying on `DYLD_LIBRARY_PATH`.

Specifically, add the following to the **CMakeLists.txt** file:

```cmake
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib;/path/to/Qt/lib;/usr/local/lib")
set(CMAKE_BUILD_RPATH "${CMAKE_INSTALL_PREFIX}/lib;/path/to/Qt/lib;/usr/local/lib")
```

- **`CMAKE_BUILD_WITH_INSTALL_RPATH`**: Ensures that RPATH is applied both during the build and installation stages.
- **`CMAKE_INSTALL_RPATH`**: Sets the runtime path for installed binaries, pointing to PCRaster libraries, Qt libraries, and other dependencies.
- **`CMAKE_BUILD_RPATH`**: Sets the runtime path for binaries during the build process.

Replace `/path/to/Qt/lib` with the appropriate path to the Qt libraries on the system, such as `/Users/ricardo/Qt/6.8.1/macos/lib`.

---

### Why This is Needed
Manually setting `DYLD_LIBRARY_PATH` works as a temporary workaround but is fragile and can interfere with other applications. Embedding the correct `RPATH` during the build process ensures:
1. Binaries like `pcrcalc`, `aguila`, and Python modules are self-contained.
2. Users do not need to modify environment variables post-installation.
3. Better compatibility with macOS System Integrity Protection (SIP).

---

This approach addresses the problem systematically and provides a robust solution for PCRaster users on macOS.

---

Finally, for me, the recommended configuration syntax would look like this:

```bash
  cmake -G"Unix Makefiles" ../pcraster \
    -DCMAKE_INSTALL_PREFIX=$HOME/pcraster-4.3.3 \
    -DCURSES_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/ \
    -DCMAKE_PREFIX_PATH=/Users/ricardo/Qt/6.8.1/macos/lib/cmake/Qt6/ \
    -DPython3_EXECUTABLE:FILEPATH=/usr/bin/python3.13 \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
    -DCMAKE_INSTALL_RPATH="/Users/ricardo/Qt/6.8.1/macos/lib;/Users/ricardo/pcraster-4.3.3/lib;/usr/local/lib" \
    -DCMAKE_BUILD_RPATH="/Users/ricardo/Qt/6.8.1/macos/lib;/Users/ricardo/pcraster-4.3.3/lib;/usr/local/lib" 
```

**Comment by OliverSchmitz** [comment]
Hello Ricardo,
thanks for reporting and solving this. The RPATH settings are already done and should work for various settings (macports, conda, brew). We'll revisit the situation of non-standard library locations though...
